name: Test downstream projects

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Test Package
        run: |

          python -m venv test
          ./test/bin/python -m pip install -U pip
          ./test/bin/python -m pip install ipykernel[test]
          ./test/bin/python -m pip install --pre -U --upgrade-strategy=only-if-needed ipykernel
          ./test/bin/python -m pip install . --force-reinstall
          ./test/bin/pytest --pyargs ipykernel
          rm -rf ./test
