name: Test downstream projects

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/action/base-setup@v1

      - name: Test Ipykernel
        uses: ./github/actions/downstream-test
        with:
          package_name: ipykernel
