name: "Downstream Test"
description: "Test against a downstream library"
inputs:
  package_name:
    description: "The downstream package name"
    required: true
  package_spec:
    description: "The package spec(s) to install, defaults to '<package_name>[test]"
  pytest_args:
    description: "The pytest args (defaults to '--pyargs <package_name>'"
  env_values:
    description: "Optional env values to set for test, e.g. 'FOO=BAR FIZZ=BUZZ'"
runs:
  using: "composite"
  steps:
    - name: set up venv
      shell: bash
      run: |
          set -x
          # Set up env values
          package_spec="${{inputs.package_spec}}"
          package_spec=${package_spec:-"${{inputs.package_name}}[test]"}
          pytest_args="${{inputs.pytest_args}}"
          pytest_args=${pytest_args:-"--pyargs ${{inputs.package_name}}"}
          eval "${{inputs.env_values}}"

          # Set up venv
          python -m venv test_venv
          export PATH=$(pwd)/test_venv/bin:$PATH
          python -m pip install -U pip
          python -m pip install ${package_spec}
          python -m pip install . --force-reinstall
          cd $HOME

          # Test the downstream package
          pytest ${pytest_args}

          # Cleanup
          rm -rf ./test_venv
